project:
  type: book
  output-dir: docs

book:
  title: "Parallel Ensemble-Kalman-Inversion"
  author: Ralph-Uwe Börner
  date: "today"
  chapters: 
    - index.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

